# Generated by Django 4.2.3 on 2023-07-06 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('answer', models.CharField(max_length=1)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=4)),
            ],
        ),
    ]
